#include <sstream>
#include <corsika/CorsikaParticle.h>
#include <boost/python.hpp>

using namespace boost::python;
using namespace corsika;

void register_CorsikaParticle()
{
  scope block_scope =
    class_<CorsikaParticle>("CorsikaParticle")
    .def("__str__", &CorsikaParticle::String)
    .add_property("pdg_code", &CorsikaParticle::PDGCode)
    .add_property("corsika_code", &CorsikaParticle::CorsikaCode)
    .add_property("name", &CorsikaParticle::GetName)
    .add_property("hadronic_generation", &CorsikaParticle::HadronicGeneration)
    .add_property("observing_level", &CorsikaParticle::ObservingLevel)
    .add_property("is_particle", &CorsikaParticle::IsParticle)
    .add_property("is_nucleus", &CorsikaParticle::IsNucleus)
    .add_property("is_cherenkov", &CorsikaParticle::IsCherenkov)
    .add_property("mass", &CorsikaParticle::Mass)
    .add_property("momentum", &CorsikaParticle::Momentum)
    .add_property("kinetic_energy", &CorsikaParticle::KineticEnergy)
    .add_property("has_parent", &CorsikaParticle::HasParent)
    .add_property("has_muon_info", &CorsikaParticle::HasMuonInfo)
    .def_readonly("description", &CorsikaParticle::fDescription)
    .def_readonly("px", &CorsikaParticle::fPx)
    .def_readonly("py", &CorsikaParticle::fPy)
    .def_readonly("pz", &CorsikaParticle::fPz)
    .def_readonly("x", &CorsikaParticle::fX)
    .def_readonly("y", &CorsikaParticle::fY)
    .def_readonly("t_or_z", &CorsikaParticle::fTorZ)
    .def_readonly("weight", &CorsikaParticle::fWeight)
    .add_property("parent",  make_function(&CorsikaParticle::GetParent, return_internal_reference<>()  ))
    .add_property("grand_parent", make_function( &CorsikaParticle::GetGrandParent, return_internal_reference<>() ) )
    .add_property("muon_info", make_function( &CorsikaParticle::GetMuonInfo, return_internal_reference<>() ) )
    .def("nucleus_code", &CorsikaParticle::NucleusCode)
    .staticmethod("nucleus_code")
    ;

  enum_<CorsikaParticle::Type>("Type")
    .value("eUndefined"        , CorsikaParticle::eUndefined)
    .value("eElectron"         , CorsikaParticle::eElectron)
    .value("ePositron"         , CorsikaParticle::ePositron)
    .value("eNuElectron"       , CorsikaParticle::eNuElectron)
    .value("eAntiNuElectron"   , CorsikaParticle::eAntiNuElectron)
    .value("eMuon"             , CorsikaParticle::eMuon)
    .value("eAntiMuon"         , CorsikaParticle::eAntiMuon)
    .value("eNuMuon"           , CorsikaParticle::eNuMuon)
    .value("eAntiNuMuon"       , CorsikaParticle::eAntiNuMuon)
    .value("eTau"              , CorsikaParticle::eTau)
    .value("eAntiTau"          , CorsikaParticle::eAntiTau)
    .value("eNuTau"            , CorsikaParticle::eNuTau)
    .value("eAntiNuTau"        , CorsikaParticle::eAntiNuTau)
    .value("ePhoton"           , CorsikaParticle::ePhoton)
    .value("ePiZero"           , CorsikaParticle::ePiZero)
    .value("eRhoZero"          , CorsikaParticle::eRhoZero)
    .value("ePiPlus"           , CorsikaParticle::ePiPlus)
    .value("ePiMinus"          , CorsikaParticle::ePiMinus)
    .value("eRhoPlus"          , CorsikaParticle::eRhoPlus)
    .value("eRhoMinus"         , CorsikaParticle::eRhoMinus)
    .value("eEta"              , CorsikaParticle::eEta)
    .value("eOmegaMeson"       , CorsikaParticle::eOmegaMeson)
    .value("eKaon0L"           , CorsikaParticle::eKaon0L)
    .value("eKaon0S"           , CorsikaParticle::eKaon0S)
    .value("eKaonPlus"         , CorsikaParticle::eKaonPlus)
    .value("eKaonMinus"        , CorsikaParticle::eKaonMinus)
    .value("eDeltaMinus"       , CorsikaParticle::eDeltaMinus)
    .value("eLambda"           , CorsikaParticle::eLambda)
    .value("eSigmaPlus"        , CorsikaParticle::eSigmaPlus)
    .value("eSigmaZero"        , CorsikaParticle::eSigmaZero)
    .value("eSigmaMinus"       , CorsikaParticle::eSigmaMinus)
    .value("eAntiSigmaPlus"    , CorsikaParticle::eAntiSigmaPlus)
    .value("eAntiSigmaZero"    , CorsikaParticle::eAntiSigmaZero)
    .value("eAntiSigmaMinus"   , CorsikaParticle::eAntiSigmaMinus)
    .value("eXiZero"           , CorsikaParticle::eXiZero)
    .value("eXiMinus"          , CorsikaParticle::eXiMinus)
    .value("eAntiXiZero"       , CorsikaParticle::eAntiXiZero)
    .value("eAntiXiMinus"      , CorsikaParticle::eAntiXiMinus)
    .value("eOmegaMinus"       , CorsikaParticle::eOmegaMinus)
    .value("eAntiOmegaMinus"   , CorsikaParticle::eAntiOmegaMinus)
    .value("eLambdac"          , CorsikaParticle::eLambdac)
    .value("eNeutron"          , CorsikaParticle::eNeutron)
    .value("eAntiNeutron"      , CorsikaParticle::eAntiNeutron)
    .value("eDeltaZero"        , CorsikaParticle::eDeltaZero)
    .value("eProton"           , CorsikaParticle::eProton)
    .value("eAntiProton"       , CorsikaParticle::eAntiProton)
    .value("eDeltaPlus"        , CorsikaParticle::eDeltaPlus)
    .value("eDeltaPlusPlus"    , CorsikaParticle::eDeltaPlusPlus)
    .value("eDecayedMuon"      , CorsikaParticle::eDecayedMuon)
    .value("eDecayedAntiMuon"  , CorsikaParticle::eDecayedAntiMuon)
    .value("eIron"             , CorsikaParticle::eIron)
    ;

}
