#include <sstream>
#include <corsika/Particle.h>
#include <boost/python.hpp>

using namespace boost::python;
using namespace corsika;

void register_Particle()
{
  scope block_scope =
    class_<Particle>("Particle")
    .def("__str__", &Particle::String)
    .add_property("pdg_code", &Particle::PDGCode)
    .add_property("corsika_code", &Particle::CorsikaCode)
    .add_property("name", &Particle::GetName)
    .add_property("hadronic_generation", &Particle::HadronicGeneration)
    .add_property("observing_level", &Particle::ObservingLevel)
    .add_property("is_particle", &Particle::IsParticle)
    .add_property("is_nucleus", &Particle::IsNucleus)
    .add_property("is_cherenkov", &Particle::IsCherenkov)
    .add_property("mass", &Particle::Mass)
    .add_property("momentum", &Particle::Momentum)
    .add_property("kinetic_energy", &Particle::KineticEnergy)
    .add_property("has_parent", &Particle::HasParent)
    .add_property("has_muon_info", &Particle::HasMuonInfo)
    .def_readonly("description", &Particle::fDescription)
    .def_readonly("px", &Particle::fPx)
    .def_readonly("py", &Particle::fPy)
    .def_readonly("pz", &Particle::fPz)
    .def_readonly("x", &Particle::fX)
    .def_readonly("y", &Particle::fY)
    .def_readonly("t_or_z", &Particle::fTorZ)
    .def_readonly("weight", &Particle::fWeight)
    .add_property("parent",  make_function(&Particle::GetParent, return_internal_reference<>()  ))
    .add_property("grand_parent", make_function( &Particle::GetGrandParent, return_internal_reference<>() ) )
    .add_property("muon_info", make_function( &Particle::GetMuonInfo, return_internal_reference<>() ) )
    .def("nucleus_code", &Particle::NucleusCode)
    .staticmethod("nucleus_code")
    ;

  enum_<Particle::Type>("Type")
    .value("eUndefined"        , Particle::eUndefined)
    .value("eElectron"         , Particle::eElectron)
    .value("ePositron"         , Particle::ePositron)
    .value("eNuElectron"       , Particle::eNuElectron)
    .value("eAntiNuElectron"   , Particle::eAntiNuElectron)
    .value("eMuon"             , Particle::eMuon)
    .value("eAntiMuon"         , Particle::eAntiMuon)
    .value("eNuMuon"           , Particle::eNuMuon)
    .value("eAntiNuMuon"       , Particle::eAntiNuMuon)
    .value("eTau"              , Particle::eTau)
    .value("eAntiTau"          , Particle::eAntiTau)
    .value("eNuTau"            , Particle::eNuTau)
    .value("eAntiNuTau"        , Particle::eAntiNuTau)
    .value("ePhoton"           , Particle::ePhoton)
    .value("ePiZero"           , Particle::ePiZero)
    .value("eRhoZero"          , Particle::eRhoZero)
    .value("ePiPlus"           , Particle::ePiPlus)
    .value("ePiMinus"          , Particle::ePiMinus)
    .value("eRhoPlus"          , Particle::eRhoPlus)
    .value("eRhoMinus"         , Particle::eRhoMinus)
    .value("eEta"              , Particle::eEta)
    .value("eOmegaMeson"       , Particle::eOmegaMeson)
    .value("eKaon0L"           , Particle::eKaon0L)
    .value("eKaon0S"           , Particle::eKaon0S)
    .value("eKaonPlus"         , Particle::eKaonPlus)
    .value("eKaonMinus"        , Particle::eKaonMinus)
    .value("eDeltaMinus"       , Particle::eDeltaMinus)
    .value("eLambda"           , Particle::eLambda)
    .value("eSigmaPlus"        , Particle::eSigmaPlus)
    .value("eSigmaZero"        , Particle::eSigmaZero)
    .value("eSigmaMinus"       , Particle::eSigmaMinus)
    .value("eAntiSigmaPlus"    , Particle::eAntiSigmaPlus)
    .value("eAntiSigmaZero"    , Particle::eAntiSigmaZero)
    .value("eAntiSigmaMinus"   , Particle::eAntiSigmaMinus)
    .value("eXiZero"           , Particle::eXiZero)
    .value("eXiMinus"          , Particle::eXiMinus)
    .value("eAntiXiZero"       , Particle::eAntiXiZero)
    .value("eAntiXiMinus"      , Particle::eAntiXiMinus)
    .value("eOmegaMinus"       , Particle::eOmegaMinus)
    .value("eAntiOmegaMinus"   , Particle::eAntiOmegaMinus)
    .value("eLambdac"          , Particle::eLambdac)
    .value("eNeutron"          , Particle::eNeutron)
    .value("eAntiNeutron"      , Particle::eAntiNeutron)
    .value("eDeltaZero"        , Particle::eDeltaZero)
    .value("eProton"           , Particle::eProton)
    .value("eAntiProton"       , Particle::eAntiProton)
    .value("eDeltaPlus"        , Particle::eDeltaPlus)
    .value("eDeltaPlusPlus"    , Particle::eDeltaPlusPlus)
    .value("eDecayedMuon"      , Particle::eDecayedMuon)
    .value("eDecayedAntiMuon"  , Particle::eDecayedAntiMuon)
    .value("eIron"             , Particle::eIron)
    ;

}
